### ISSUE TITLE
I am reading this and....

### ISSUE THREAD

**Issue by isaac-weisberg** [BohdanOrlov/ios-skills-matrix#1]
well nice job really, that's actually some good observations, but as of my practice, it's more chaotic in real life than this. So chaotic, that these... entitlements, skill tree, right, these become less about the actual skill but rather more about what you yourself desire, dare to do :) But it's incredible how much time you investigate this stuff)

**Comment by BohdanOrlov** [comment]
Hey @isaac-weisberg, thank you for the comment! I agree with you that the matrix doesn't reflect the whole story. In fact, the further we improve our hard skills the more we realise that the bottleneck in our job is human themselves with their desires and fears. So that we have to be brave enough do to things which are scary and might fail ;)
